name: Node.js CI/CD

on:
  push:
    branches:
      - main   # runs when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: 1. Checkout code
      uses: actions/checkout@v3

    - name: 2. Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: 3. Install dependencies
      run: npm install

    - name: 4. Run app (test step)
      run: echo "App build successful"
